title: Nick's Amazon Deals
description: Curated Amazon deals and discounts.
baseurl: "/amzaff"
url: "https://nickscbr.github.io"

sass:
  style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact